### ISSUE TITLE
Error while executing BLINK

### ISSUE THREAD

**Issue by ga23981** [YaoZhou89/BLINK#2]
myBlink=Blink(Y=myY,GD=myGD,GM=myGM,maxLoop=10,time.cal=T)
[1] "----------------------Welcome to Blink----------------------"
[1] "----------------------Iteration: 1 ----------------------"
[1] "seqQTN:"
NULL
Error in seq.default(1, nchr, by = ncycle) : invalid '(to - from)/by'
In addition: There were 50 or more warnings (use warnings() to see the first 50)
> warnings()
Warning messages:
1: In diag(iXX) * ve :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

2: In diag(iXX) * ve :
  Recycling array of length 1 in vector-array arithmetic is deprecated.
  Use c() or as.vector() instead.

**Comment by YaoZhou89** [comment]
It seems that the problem caused by input format. You could debug using the following code:
head(myGM)
dim(myGM)
dim(myGM)

**Comment by ga23981** [comment]
> head(myGM)
               snp_id         CHROM   POS
1 NZ_CP020943.1_12213 NZ_CP020943.1 12213
2 NZ_CP020943.1_12214 NZ_CP020943.1 12214
3 NZ_CP020943.1_12215 NZ_CP020943.1 12215
4 NZ_CP020943.1_12220 NZ_CP020943.1 12220
5 NZ_CP020943.1_12226 NZ_CP020943.1 12226
6 NZ_CP020943.1_12235 NZ_CP020943.1 12235
> dim(myGM)
[1] 63265     3
> dim(myGM)
[1] 63265     3
> myBlink=Blink(Y=myY,GD=myGD,GM=myGM,maxLoop=10,time.cal=T)
[1] "----------------------Welcome to Blink----------------------"
[1] "----------------------Iteration: 1 ----------------------"
[1] "seqQTN:"
NULL
Error in seq.default(1, nchr, by = ncycle) : invalid '(to - from)/by'
In addition: There were 50 or more warnings (use warnings() to see the first 50)

**Comment by ga23981** [comment]
Is it the chromosome name that is causing the problem? Should it be a numeric value?

**Comment by ga23981** [comment]
Hello Yao,

I tried what you suggested in your previous mail but the error is still the
same.

Would you mind if I share with you my data files in case you would like to
test them at your end?

Thank you
Gaurav

**Comment by YaoZhou89** [comment]
It will be better if you could share your data.

 

Best regards,

Yao

**Comment by ga23981** [comment]
Files are attached herewith.

Thank you

**Comment by YaoZhou89** [comment]
Could you please send me the files again? I didn’t see any file.

 

Best regards,

Yao

**Comment by ga23981** [comment]
[blink_association.zip](https://github.com/YaoZhou89/BLINK/files/3335248/blink_association.zip)

**Comment by ga23981** [comment]
blink_association.zip
<https://github.com/YaoZhou89/BLINK/files/3335248/blink_association.zip>

Please see a zipped folder as above shared on github.

Gaurav

**Comment by YaoZhou89** [comment]
Thanks!

 

Best regards,

Yao

**Comment by ga23981** [comment]
Hello Yao,

Could you get time to look into my files?

Thanks
Gaurav

**Comment by ga23981** [comment]
Hello Yao,

Please suggest me if there is any issue with the data files itself?

Thank you
Gaurav

**Comment by ga23981** [comment]
Hello Meng,
I started the data analysis again and reached until this step:
myY =
read.table("/scratch/ga23981/bglab/pantoea_alignment/vcf_raw_filter/gwas/blink/data.txt",head=F,sep="\t",type="char"",head
= T)
after entering the above script it just gives me
+

something like this,

> myY =
read.table("/scratch/ga23981/bglab/pantoea_alignment/vcf_raw_filter/gwas/blink/data.txt",head=F,sep="\t",type="char"",head
= T)
+
+
+
+
+
+
+

Please suggest!

Thank you
Gaurav
