### ISSUE TITLE
Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x' when calculating PCs

### ISSUE THREAD

**Issue by justdx** [YaoZhou89/BLINK#3]
Hello, Yao.

I am running BLINK on my data for GWAS analysis. It worked well for the standard procedure, but when I calculated PCs using prcomp, it showed an error of "Error in svd(x, nu = 0, nv = k) : infinite or missing values in 'x'".

I found the error was due to the "NA" representing the missing genotype in *.dat file. I have also tried "Na", "na" or "NaN", but these did not solve the problem. So I would like to ask what is a proper symbol for missing genotype when calculate PC?

**Comment by YaoZhou89** [comment]
Hi, 

 

Missing values are not supported in covariate file. You could only use other software (e.g. Plink) to calculate PCs firstly. You can use the PCs as  covariates by myCV=PCs_file.txt in BLINK.

 

Best regards,

Yao
