### ISSUE TITLE
BLINK installiation

### ISSUE THREAD

**Issue by AshokMandal** [YaoZhou89/BLINK#4]
i tried to install BLINK for GWAS analysis but it shows following error
Error: Failed to install 'BLINK' from GitHub:
  (converted from warning) cannot remove prior installation of package ‘Rcpp’
Actually, it used to download automatically from GAPIT when i selected model "BLINK"
 
Anybody could help me.

**Comment by mural123** [comment]
Did you try updating R?

**Comment by ravimural** [comment]
Can you update R to newer version and try to install BLINK?

**Comment by AshokMandal** [comment]
Yeah,  i already did it works fine after update. Thank you for your response.
