### ISSUE TITLE
Error in cleanupcols(cols, ncol(x), colnames(x)) :   Illegal column index usage in extraction.

### ISSUE THREAD

**Issue by Elakhdar** [YaoZhou89/BLINK#6]
Hi Yao,
I got the following error, while I am running BLINK to analysis GWAs.

I used "NA" for myData.dat file as missing values.
thanks :)

> setwd("~/Documents/GitHub/BLINK/data")
> myGM=read.table("myData.map",head=T)
> myGD=read.big.matrix("myData.dat",head=F,sep="\t",type="char") 
> myY = read.table("myData.txt",head = T) 
> myBlink=Blink(Y=myY,GD=myGD,GM=myGM,maxLoop=10,time.cal=T)
[1] "----------------------Welcome to Blink----------------------"
### Error in cleanupcols(cols, ncol(x), colnames(x)) : 
  Illegal column index usage in extraction.
Called from: cleanupcols(cols, ncol(x), colnames(x))
Browse[1]>

**Comment by YaoZhou89** [comment]
I never see this error before; you could try: traceback() to debug. And please pay attention to the input data format.

**Comment by Elakhdar** [comment]
Thanks a lot Yao, I fixed the issue.

However, how could I remove SNPs missing in all samples?
"Quality filtration of SNP markers"

**Comment by jimblobf** [comment]
How did you fix the original issue? I am having the same error.

**Comment by YaoZhou89** [comment]
You could try traceback() to debug. And please pay attention to the input data format.
