### ISSUE TITLE
BLINK.R does not print results into working directory

### ISSUE THREAD

**Issue by mshehabu** [YaoZhou89/BLINK#8]
I have been using BLINK.R for GWAS. now when I try it after a while, it doesn't send the results in the working directory
would you please help?

**Comment by YaoZhou89** [comment]
Is there any significant variant identified? BLINK R version only output significant variants.

**Comment by mshehabu** [comment]
Thanks for your response!
yes, there are
I have checked it using data that generated results previously. I couldn't
repeat what I did before

Meki

**Comment by mshehabu** [comment]
and i used the following syntax;

getwd()
library(BLINK)
library(MASS) # required for ginv
library(multtest)
library(gplots)
library(compiler) #required for cmpfun
library(scatterplot3d)

source("http://zzlab.net/FarmCPU/FarmCPU_functions.txt")
source("http://zzlab.net/GAPIT/gapit_functions.txt")

myGM=read.table("snpData2.map",head=T)
myGD=read.big.matrix("snpData2.dat",head=F, sep="\t",type="char")
myY = read.table("snpData2.txt",head = T, sep="\t")
myCV = read.table("myData.cov",head = T, sep="\t", row.names = 1)

for (i in 2:ncol(myY)){
  myBlink=Blink(Y=myY[,c(1,i)],GD=myGD,GM=myGM,CV = myCV,
maxLoop=10,time.cal=T, maf.threshold=0.05)
}

**Comment by mshehabu** [comment]
Hi Yao,
in my GWAS analysis, I found many markers discriminating between white and
black/dark-brown seed colors. What surprised me is that the markers are
distributed all over the genome and detected in all chromosomes. This is
unusual for me, in case if you have a similar experience or if you know
someone who can give me his advise?

Thanks,
Meki
